name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v1.3.0
      with:
        # private SSH key
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        # public SSH key
        public-key: ${{ secrets.SSH_PUBLIC_KEY }}
        # SSH key file name (default: id_rsa)
        name: id_rsa
        # public keys of SSH servers
        known-hosts: "gomano.de"
    - name: Test ssh
      run: ssh root@gomano.de 'touch /tmp/hello'
